### ISSUE TITLE
求如何改自己统一的地址

### ISSUE THREAD

**Issue by spiritLHL** [dishuihengxin/lovelt-kalid#1]
大佬，之前的帖子没有消息了，请问怎么改呢？

**Comment by dishuihengxin** [comment]
改什么？

**Comment by spiritLHL** [comment]
这个

**Comment by spiritLHL** [comment]
传不上去。。。过会我拿电脑传吧

**Comment by spiritLHL** [comment]
https://github.com/spiritLHL/spiritLHL.github.io/issues/1
![](https://user-images.githubusercontent.com/20619983/124534725-6b597080-de47-11eb-8bf4-106bae53fa01.png)

**Comment by spiritLHL** [comment]
这个

**Comment by dishuihengxin** [comment]
`layouts/partials/head/seo.html` 我是放在这个 template 里面了，你修改一下重新build 就可以了。

**Comment by spiritLHL** [comment]
已删除，谢谢指导
